import type { Metadata } from 'next';
import './globals.css';
import { Header } from '@/app/header';

export const metadata: Metadata = {
  title: 'SnapCards',
  description: 'Generated by create next app',
};



export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      {children}
    </>
  );
}
